{% set name = "nb_cron" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/n/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64a3b1672a2367749336c00d9edd722f44653f671efd36a1c7b0eae51aae5d44

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - jupyter nbextension install nb_cron --py --sys-prefix --overwrite
  skip: true  # [win or python_impl == 'pypy']

requirements:
  host:
    - python
    - setuptools
    - pip
    - notebook >=4.3.1
    - python-crontab
  run:
    - python
    - notebook >=4.3.1
    - traitlets
    - tornado
    - python-crontab
    - croniter

test:
  source_files:
    - setup.cfg
    - .coveragerc
    - tests
  requires:
    - pytest
    - pytest-cov
    - requests
    - selenium
    - geckodriver
  commands:
    - pytest

about:
  home: https://github.com/alexanghh/nb_cron
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cron tab access extension from within Jupyter
  description: |
    nb_cron is a simple tool to allow managing of crontab from within Jupyter.
  dev_url: https://github.com/alexanghh/nb_cron

extra:
  recipe-maintainers:
    - alexanghh
